/*
upbot API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StoreANewlyCreatedResourceInStorage201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreANewlyCreatedResourceInStorage201Response{}

// StoreANewlyCreatedResourceInStorage201Response struct for StoreANewlyCreatedResourceInStorage201Response
type StoreANewlyCreatedResourceInStorage201Response struct {
	Id *string `json:"id,omitempty"`
}

// NewStoreANewlyCreatedResourceInStorage201Response instantiates a new StoreANewlyCreatedResourceInStorage201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreANewlyCreatedResourceInStorage201Response() *StoreANewlyCreatedResourceInStorage201Response {
	this := StoreANewlyCreatedResourceInStorage201Response{}
	return &this
}

// NewStoreANewlyCreatedResourceInStorage201ResponseWithDefaults instantiates a new StoreANewlyCreatedResourceInStorage201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreANewlyCreatedResourceInStorage201ResponseWithDefaults() *StoreANewlyCreatedResourceInStorage201Response {
	this := StoreANewlyCreatedResourceInStorage201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StoreANewlyCreatedResourceInStorage201Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreANewlyCreatedResourceInStorage201Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StoreANewlyCreatedResourceInStorage201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StoreANewlyCreatedResourceInStorage201Response) SetId(v string) {
	o.Id = &v
}

func (o StoreANewlyCreatedResourceInStorage201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreANewlyCreatedResourceInStorage201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableStoreANewlyCreatedResourceInStorage201Response struct {
	value *StoreANewlyCreatedResourceInStorage201Response
	isSet bool
}

func (v NullableStoreANewlyCreatedResourceInStorage201Response) Get() *StoreANewlyCreatedResourceInStorage201Response {
	return v.value
}

func (v *NullableStoreANewlyCreatedResourceInStorage201Response) Set(val *StoreANewlyCreatedResourceInStorage201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreANewlyCreatedResourceInStorage201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreANewlyCreatedResourceInStorage201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreANewlyCreatedResourceInStorage201Response(val *StoreANewlyCreatedResourceInStorage201Response) *NullableStoreANewlyCreatedResourceInStorage201Response {
	return &NullableStoreANewlyCreatedResourceInStorage201Response{value: val, isSet: true}
}

func (v NullableStoreANewlyCreatedResourceInStorage201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreANewlyCreatedResourceInStorage201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


