/*
upbot API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbot

import (
	"encoding/json"
)

// checks if the DisplayAListingOfTheResource200ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisplayAListingOfTheResource200ResponseMeta{}

// DisplayAListingOfTheResource200ResponseMeta struct for DisplayAListingOfTheResource200ResponseMeta
type DisplayAListingOfTheResource200ResponseMeta struct {
	CurrentPage *int32 `json:"current_page,omitempty"`
	CurrentPageUrl *string `json:"current_page_url,omitempty"`
	From *int32 `json:"from,omitempty"`
	Path *string `json:"path,omitempty"`
	PerPage *string `json:"per_page,omitempty"`
	To *int32 `json:"to,omitempty"`
}

// NewDisplayAListingOfTheResource200ResponseMeta instantiates a new DisplayAListingOfTheResource200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisplayAListingOfTheResource200ResponseMeta() *DisplayAListingOfTheResource200ResponseMeta {
	this := DisplayAListingOfTheResource200ResponseMeta{}
	return &this
}

// NewDisplayAListingOfTheResource200ResponseMetaWithDefaults instantiates a new DisplayAListingOfTheResource200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisplayAListingOfTheResource200ResponseMetaWithDefaults() *DisplayAListingOfTheResource200ResponseMeta {
	this := DisplayAListingOfTheResource200ResponseMeta{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *DisplayAListingOfTheResource200ResponseMeta) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetCurrentPageUrl returns the CurrentPageUrl field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetCurrentPageUrl() string {
	if o == nil || IsNil(o.CurrentPageUrl) {
		var ret string
		return ret
	}
	return *o.CurrentPageUrl
}

// GetCurrentPageUrlOk returns a tuple with the CurrentPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetCurrentPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentPageUrl) {
		return nil, false
	}
	return o.CurrentPageUrl, true
}

// HasCurrentPageUrl returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) HasCurrentPageUrl() bool {
	if o != nil && !IsNil(o.CurrentPageUrl) {
		return true
	}

	return false
}

// SetCurrentPageUrl gets a reference to the given string and assigns it to the CurrentPageUrl field.
func (o *DisplayAListingOfTheResource200ResponseMeta) SetCurrentPageUrl(v string) {
	o.CurrentPageUrl = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetFrom() int32 {
	if o == nil || IsNil(o.From) {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetFromOk() (*int32, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *DisplayAListingOfTheResource200ResponseMeta) SetFrom(v int32) {
	o.From = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *DisplayAListingOfTheResource200ResponseMeta) SetPath(v string) {
	o.Path = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetPerPage() string {
	if o == nil || IsNil(o.PerPage) {
		var ret string
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetPerPageOk() (*string, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given string and assigns it to the PerPage field.
func (o *DisplayAListingOfTheResource200ResponseMeta) SetPerPage(v string) {
	o.PerPage = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetTo() int32 {
	if o == nil || IsNil(o.To) {
		var ret int32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) GetToOk() (*int32, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseMeta) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given int32 and assigns it to the To field.
func (o *DisplayAListingOfTheResource200ResponseMeta) SetTo(v int32) {
	o.To = &v
}

func (o DisplayAListingOfTheResource200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisplayAListingOfTheResource200ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	if !IsNil(o.CurrentPageUrl) {
		toSerialize["current_page_url"] = o.CurrentPageUrl
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableDisplayAListingOfTheResource200ResponseMeta struct {
	value *DisplayAListingOfTheResource200ResponseMeta
	isSet bool
}

func (v NullableDisplayAListingOfTheResource200ResponseMeta) Get() *DisplayAListingOfTheResource200ResponseMeta {
	return v.value
}

func (v *NullableDisplayAListingOfTheResource200ResponseMeta) Set(val *DisplayAListingOfTheResource200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableDisplayAListingOfTheResource200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableDisplayAListingOfTheResource200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisplayAListingOfTheResource200ResponseMeta(val *DisplayAListingOfTheResource200ResponseMeta) *NullableDisplayAListingOfTheResource200ResponseMeta {
	return &NullableDisplayAListingOfTheResource200ResponseMeta{value: val, isSet: true}
}

func (v NullableDisplayAListingOfTheResource200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisplayAListingOfTheResource200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


