/*
upbot API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbot

import (
	"encoding/json"
)

// checks if the DisplayAListingOfTheResource200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisplayAListingOfTheResource200ResponseDataInner{}

// DisplayAListingOfTheResource200ResponseDataInner struct for DisplayAListingOfTheResource200ResponseDataInner
type DisplayAListingOfTheResource200ResponseDataInner struct {
	Id *string `json:"id,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	Type *string `json:"type,omitempty"`
	Target *string `json:"target,omitempty"`
	Interval *int32 `json:"interval,omitempty"`
	Status *string `json:"status,omitempty"`
	RetryCount *int32 `json:"retry_count,omitempty"`
	AvatarUrl *string `json:"avatar_url,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Bot *string `json:"bot,omitempty"`
}

// NewDisplayAListingOfTheResource200ResponseDataInner instantiates a new DisplayAListingOfTheResource200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisplayAListingOfTheResource200ResponseDataInner() *DisplayAListingOfTheResource200ResponseDataInner {
	this := DisplayAListingOfTheResource200ResponseDataInner{}
	return &this
}

// NewDisplayAListingOfTheResource200ResponseDataInnerWithDefaults instantiates a new DisplayAListingOfTheResource200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisplayAListingOfTheResource200ResponseDataInnerWithDefaults() *DisplayAListingOfTheResource200ResponseDataInner {
	this := DisplayAListingOfTheResource200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetId(v string) {
	o.Id = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetType(v string) {
	o.Type = &v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetTarget(v string) {
	o.Target = &v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetInterval() int32 {
	if o == nil || IsNil(o.Interval) {
		var ret int32
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetIntervalOk() (*int32, bool) {
	if o == nil || IsNil(o.Interval) {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasInterval() bool {
	if o != nil && !IsNil(o.Interval) {
		return true
	}

	return false
}

// SetInterval gets a reference to the given int32 and assigns it to the Interval field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetInterval(v int32) {
	o.Interval = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetStatus(v string) {
	o.Status = &v
}

// GetRetryCount returns the RetryCount field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetRetryCount() int32 {
	if o == nil || IsNil(o.RetryCount) {
		var ret int32
		return ret
	}
	return *o.RetryCount
}

// GetRetryCountOk returns a tuple with the RetryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetRetryCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryCount) {
		return nil, false
	}
	return o.RetryCount, true
}

// HasRetryCount returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasRetryCount() bool {
	if o != nil && !IsNil(o.RetryCount) {
		return true
	}

	return false
}

// SetRetryCount gets a reference to the given int32 and assigns it to the RetryCount field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetRetryCount(v int32) {
	o.RetryCount = &v
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetBot returns the Bot field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetBot() string {
	if o == nil || IsNil(o.Bot) {
		var ret string
		return ret
	}
	return *o.Bot
}

// GetBotOk returns a tuple with the Bot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) GetBotOk() (*string, bool) {
	if o == nil || IsNil(o.Bot) {
		return nil, false
	}
	return o.Bot, true
}

// HasBot returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseDataInner) HasBot() bool {
	if o != nil && !IsNil(o.Bot) {
		return true
	}

	return false
}

// SetBot gets a reference to the given string and assigns it to the Bot field.
func (o *DisplayAListingOfTheResource200ResponseDataInner) SetBot(v string) {
	o.Bot = &v
}

func (o DisplayAListingOfTheResource200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisplayAListingOfTheResource200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	if !IsNil(o.Interval) {
		toSerialize["interval"] = o.Interval
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RetryCount) {
		toSerialize["retry_count"] = o.RetryCount
	}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Bot) {
		toSerialize["bot"] = o.Bot
	}
	return toSerialize, nil
}

type NullableDisplayAListingOfTheResource200ResponseDataInner struct {
	value *DisplayAListingOfTheResource200ResponseDataInner
	isSet bool
}

func (v NullableDisplayAListingOfTheResource200ResponseDataInner) Get() *DisplayAListingOfTheResource200ResponseDataInner {
	return v.value
}

func (v *NullableDisplayAListingOfTheResource200ResponseDataInner) Set(val *DisplayAListingOfTheResource200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDisplayAListingOfTheResource200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDisplayAListingOfTheResource200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisplayAListingOfTheResource200ResponseDataInner(val *DisplayAListingOfTheResource200ResponseDataInner) *NullableDisplayAListingOfTheResource200ResponseDataInner {
	return &NullableDisplayAListingOfTheResource200ResponseDataInner{value: val, isSet: true}
}

func (v NullableDisplayAListingOfTheResource200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisplayAListingOfTheResource200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


