/*
upbot API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbot

import (
	"encoding/json"
)

// checks if the DisplayAListingOfTheResource200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisplayAListingOfTheResource200ResponseLinks{}

// DisplayAListingOfTheResource200ResponseLinks struct for DisplayAListingOfTheResource200ResponseLinks
type DisplayAListingOfTheResource200ResponseLinks struct {
	First *string `json:"first,omitempty"`
	Last *string `json:"last,omitempty"`
	Prev *string `json:"prev,omitempty"`
	Next *string `json:"next,omitempty"`
}

// NewDisplayAListingOfTheResource200ResponseLinks instantiates a new DisplayAListingOfTheResource200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisplayAListingOfTheResource200ResponseLinks() *DisplayAListingOfTheResource200ResponseLinks {
	this := DisplayAListingOfTheResource200ResponseLinks{}
	return &this
}

// NewDisplayAListingOfTheResource200ResponseLinksWithDefaults instantiates a new DisplayAListingOfTheResource200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisplayAListingOfTheResource200ResponseLinksWithDefaults() *DisplayAListingOfTheResource200ResponseLinks {
	this := DisplayAListingOfTheResource200ResponseLinks{}
	return &this
}

// GetFirst returns the First field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseLinks) GetFirst() string {
	if o == nil || IsNil(o.First) {
		var ret string
		return ret
	}
	return *o.First
}

// GetFirstOk returns a tuple with the First field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseLinks) GetFirstOk() (*string, bool) {
	if o == nil || IsNil(o.First) {
		return nil, false
	}
	return o.First, true
}

// HasFirst returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseLinks) HasFirst() bool {
	if o != nil && !IsNil(o.First) {
		return true
	}

	return false
}

// SetFirst gets a reference to the given string and assigns it to the First field.
func (o *DisplayAListingOfTheResource200ResponseLinks) SetFirst(v string) {
	o.First = &v
}

// GetLast returns the Last field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseLinks) GetLast() string {
	if o == nil || IsNil(o.Last) {
		var ret string
		return ret
	}
	return *o.Last
}

// GetLastOk returns a tuple with the Last field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseLinks) GetLastOk() (*string, bool) {
	if o == nil || IsNil(o.Last) {
		return nil, false
	}
	return o.Last, true
}

// HasLast returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseLinks) HasLast() bool {
	if o != nil && !IsNil(o.Last) {
		return true
	}

	return false
}

// SetLast gets a reference to the given string and assigns it to the Last field.
func (o *DisplayAListingOfTheResource200ResponseLinks) SetLast(v string) {
	o.Last = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseLinks) GetPrev() string {
	if o == nil || IsNil(o.Prev) {
		var ret string
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseLinks) GetPrevOk() (*string, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given string and assigns it to the Prev field.
func (o *DisplayAListingOfTheResource200ResponseLinks) SetPrev(v string) {
	o.Prev = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200ResponseLinks) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200ResponseLinks) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *DisplayAListingOfTheResource200ResponseLinks) SetNext(v string) {
	o.Next = &v
}

func (o DisplayAListingOfTheResource200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisplayAListingOfTheResource200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.First) {
		toSerialize["first"] = o.First
	}
	if !IsNil(o.Last) {
		toSerialize["last"] = o.Last
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	return toSerialize, nil
}

type NullableDisplayAListingOfTheResource200ResponseLinks struct {
	value *DisplayAListingOfTheResource200ResponseLinks
	isSet bool
}

func (v NullableDisplayAListingOfTheResource200ResponseLinks) Get() *DisplayAListingOfTheResource200ResponseLinks {
	return v.value
}

func (v *NullableDisplayAListingOfTheResource200ResponseLinks) Set(val *DisplayAListingOfTheResource200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableDisplayAListingOfTheResource200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableDisplayAListingOfTheResource200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisplayAListingOfTheResource200ResponseLinks(val *DisplayAListingOfTheResource200ResponseLinks) *NullableDisplayAListingOfTheResource200ResponseLinks {
	return &NullableDisplayAListingOfTheResource200ResponseLinks{value: val, isSet: true}
}

func (v NullableDisplayAListingOfTheResource200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisplayAListingOfTheResource200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


