/*
upbot API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbot

import (
	"encoding/json"
)

// checks if the StoreANewlyCreatedResourceInStorageRequestBot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreANewlyCreatedResourceInStorageRequestBot{}

// StoreANewlyCreatedResourceInStorageRequestBot This field is required when <code>type</code> is <code>discord_bot</code>.
type StoreANewlyCreatedResourceInStorageRequestBot struct {
	// This field is required when <code>type</code> is <code>discord_bot</code>. Must match the regex /^\\d{17,19}$/.
	DiscordBotId *string `json:"discord_bot_id,omitempty"`
	// This field is required when <code>type</code> is <code>discord_bot</code>. Must match the regex /^\\d{17,19}$/.
	DiscordGuildId *string `json:"discord_guild_id,omitempty"`
}

// NewStoreANewlyCreatedResourceInStorageRequestBot instantiates a new StoreANewlyCreatedResourceInStorageRequestBot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreANewlyCreatedResourceInStorageRequestBot() *StoreANewlyCreatedResourceInStorageRequestBot {
	this := StoreANewlyCreatedResourceInStorageRequestBot{}
	return &this
}

// NewStoreANewlyCreatedResourceInStorageRequestBotWithDefaults instantiates a new StoreANewlyCreatedResourceInStorageRequestBot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreANewlyCreatedResourceInStorageRequestBotWithDefaults() *StoreANewlyCreatedResourceInStorageRequestBot {
	this := StoreANewlyCreatedResourceInStorageRequestBot{}
	return &this
}

// GetDiscordBotId returns the DiscordBotId field value if set, zero value otherwise.
func (o *StoreANewlyCreatedResourceInStorageRequestBot) GetDiscordBotId() string {
	if o == nil || IsNil(o.DiscordBotId) {
		var ret string
		return ret
	}
	return *o.DiscordBotId
}

// GetDiscordBotIdOk returns a tuple with the DiscordBotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreANewlyCreatedResourceInStorageRequestBot) GetDiscordBotIdOk() (*string, bool) {
	if o == nil || IsNil(o.DiscordBotId) {
		return nil, false
	}
	return o.DiscordBotId, true
}

// HasDiscordBotId returns a boolean if a field has been set.
func (o *StoreANewlyCreatedResourceInStorageRequestBot) HasDiscordBotId() bool {
	if o != nil && !IsNil(o.DiscordBotId) {
		return true
	}

	return false
}

// SetDiscordBotId gets a reference to the given string and assigns it to the DiscordBotId field.
func (o *StoreANewlyCreatedResourceInStorageRequestBot) SetDiscordBotId(v string) {
	o.DiscordBotId = &v
}

// GetDiscordGuildId returns the DiscordGuildId field value if set, zero value otherwise.
func (o *StoreANewlyCreatedResourceInStorageRequestBot) GetDiscordGuildId() string {
	if o == nil || IsNil(o.DiscordGuildId) {
		var ret string
		return ret
	}
	return *o.DiscordGuildId
}

// GetDiscordGuildIdOk returns a tuple with the DiscordGuildId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreANewlyCreatedResourceInStorageRequestBot) GetDiscordGuildIdOk() (*string, bool) {
	if o == nil || IsNil(o.DiscordGuildId) {
		return nil, false
	}
	return o.DiscordGuildId, true
}

// HasDiscordGuildId returns a boolean if a field has been set.
func (o *StoreANewlyCreatedResourceInStorageRequestBot) HasDiscordGuildId() bool {
	if o != nil && !IsNil(o.DiscordGuildId) {
		return true
	}

	return false
}

// SetDiscordGuildId gets a reference to the given string and assigns it to the DiscordGuildId field.
func (o *StoreANewlyCreatedResourceInStorageRequestBot) SetDiscordGuildId(v string) {
	o.DiscordGuildId = &v
}

func (o StoreANewlyCreatedResourceInStorageRequestBot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreANewlyCreatedResourceInStorageRequestBot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiscordBotId) {
		toSerialize["discord_bot_id"] = o.DiscordBotId
	}
	if !IsNil(o.DiscordGuildId) {
		toSerialize["discord_guild_id"] = o.DiscordGuildId
	}
	return toSerialize, nil
}

type NullableStoreANewlyCreatedResourceInStorageRequestBot struct {
	value *StoreANewlyCreatedResourceInStorageRequestBot
	isSet bool
}

func (v NullableStoreANewlyCreatedResourceInStorageRequestBot) Get() *StoreANewlyCreatedResourceInStorageRequestBot {
	return v.value
}

func (v *NullableStoreANewlyCreatedResourceInStorageRequestBot) Set(val *StoreANewlyCreatedResourceInStorageRequestBot) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreANewlyCreatedResourceInStorageRequestBot) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreANewlyCreatedResourceInStorageRequestBot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreANewlyCreatedResourceInStorageRequestBot(val *StoreANewlyCreatedResourceInStorageRequestBot) *NullableStoreANewlyCreatedResourceInStorageRequestBot {
	return &NullableStoreANewlyCreatedResourceInStorageRequestBot{value: val, isSet: true}
}

func (v NullableStoreANewlyCreatedResourceInStorageRequestBot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreANewlyCreatedResourceInStorageRequestBot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


