/*
upbot API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DisplayAListingOfTheResource200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisplayAListingOfTheResource200Response{}

// DisplayAListingOfTheResource200Response struct for DisplayAListingOfTheResource200Response
type DisplayAListingOfTheResource200Response struct {
	Data []DisplayAListingOfTheResource200ResponseDataInner `json:"data,omitempty"`
	Links *DisplayAListingOfTheResource200ResponseLinks `json:"links,omitempty"`
	Meta *DisplayAListingOfTheResource200ResponseMeta `json:"meta,omitempty"`
}

// NewDisplayAListingOfTheResource200Response instantiates a new DisplayAListingOfTheResource200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisplayAListingOfTheResource200Response() *DisplayAListingOfTheResource200Response {
	this := DisplayAListingOfTheResource200Response{}
	return &this
}

// NewDisplayAListingOfTheResource200ResponseWithDefaults instantiates a new DisplayAListingOfTheResource200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisplayAListingOfTheResource200ResponseWithDefaults() *DisplayAListingOfTheResource200Response {
	this := DisplayAListingOfTheResource200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200Response) GetData() []DisplayAListingOfTheResource200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []DisplayAListingOfTheResource200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200Response) GetDataOk() ([]DisplayAListingOfTheResource200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DisplayAListingOfTheResource200ResponseDataInner and assigns it to the Data field.
func (o *DisplayAListingOfTheResource200Response) SetData(v []DisplayAListingOfTheResource200ResponseDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200Response) GetLinks() DisplayAListingOfTheResource200ResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret DisplayAListingOfTheResource200ResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200Response) GetLinksOk() (*DisplayAListingOfTheResource200ResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given DisplayAListingOfTheResource200ResponseLinks and assigns it to the Links field.
func (o *DisplayAListingOfTheResource200Response) SetLinks(v DisplayAListingOfTheResource200ResponseLinks) {
	o.Links = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *DisplayAListingOfTheResource200Response) GetMeta() DisplayAListingOfTheResource200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret DisplayAListingOfTheResource200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayAListingOfTheResource200Response) GetMetaOk() (*DisplayAListingOfTheResource200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *DisplayAListingOfTheResource200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given DisplayAListingOfTheResource200ResponseMeta and assigns it to the Meta field.
func (o *DisplayAListingOfTheResource200Response) SetMeta(v DisplayAListingOfTheResource200ResponseMeta) {
	o.Meta = &v
}

func (o DisplayAListingOfTheResource200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisplayAListingOfTheResource200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableDisplayAListingOfTheResource200Response struct {
	value *DisplayAListingOfTheResource200Response
	isSet bool
}

func (v NullableDisplayAListingOfTheResource200Response) Get() *DisplayAListingOfTheResource200Response {
	return v.value
}

func (v *NullableDisplayAListingOfTheResource200Response) Set(val *DisplayAListingOfTheResource200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDisplayAListingOfTheResource200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDisplayAListingOfTheResource200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisplayAListingOfTheResource200Response(val *DisplayAListingOfTheResource200Response) *NullableDisplayAListingOfTheResource200Response {
	return &NullableDisplayAListingOfTheResource200Response{value: val, isSet: true}
}

func (v NullableDisplayAListingOfTheResource200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisplayAListingOfTheResource200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


