name: Generate SDKs

on:
  push:
    paths:
      - 'openapi.yaml'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate Go SDK
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: go
          openapi-file: openapi.yaml
          command-args:  --skip-validate-spec --git-user-id upbothq --git-repo-id upbot-go-sdk

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Regenerate SDK"
          git push

      - name: Commit & Push SDKs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Regenerate SDK"
          git push
